name: Code Quality & Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black mypy pytest

    - name: Run Linter (flake8)
      run: |
        if [ -d "project_code" ] && [ "$(ls -A project_code)" ]; then
          echo "Running flake8 on project_code/"
          flake8 project_code/ --count --show-source --statistics
        else
          echo "Skipping flake8: project_code/ does not exist or is empty"
        fi

    - name: Code Format Check (black)
      run: |
        if [ -d "project_code" ] && [ "$(ls -A project_code)" ]; then
          echo "Running black on project_code/"
          black --check project_code/
        else
          echo "Skipping black: project_code/ does not exist or is empty"
        fi

    - name: Type Check (mypy)
      run: |
        if [ -d "project_code" ] && [ "$(ls -A project_code)" ]; then
          echo "Running mypy on project_code/"
          mypy project_code/
        else
          echo "Skipping mypy: project_code/ does not exist or is empty"
        fi

    - name: Run Tests (pytest)
      run: |
        if [ -d "tests" ] && [ "$(ls -A tests)" ]; then
          echo "Running tests"
          pytest tests/
        else
          echo "Skipping tests: tests/ does not exist or is empty"
        fi
