name: Code Quality & Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black mypy pytest

    - name: Run Linter (flake8)
      run: flake8 project_code/ --count --show-source --statistics

    - name: Code Format Check (black)
      run: black --check project_code/

    - name: Type Check (mypy)
      run: mypy project_code/

    - name: Run Tests (pytest)
      run: pytest tests/
